### ISSUE TITLE
Review keycloack authorization services

### ISSUE THREAD

**Issue by nancymuyeh** [ADORSYS-GIS/webank#22]
Read and understand keyclaok authorization services [Keyclaok authorisation services](https://www.keycloak.org/docs/latest/authorization_services/index.html)
And implement it in [Ledgers](https://git.adorsys.de/adorsys/xs2a/ledgers)

**Comment by Blindspot22** [comment]
@nancymuyeh  No Description ??
If I'm asked to review or work on such a ticket, I would love to have a small description(Aim) on what is happening or what has been done so far.
Thanks for understanding :raised_hands:
