### ISSUE TITLE
Wazuh onboarding

### ISSUE THREAD

**Issue by NkwaTambe** [ADORSYS-GIS/webank#23]
**Description:**

We are onboarding Wazuh agents to enhance our system’s security monitoring and threat detection capabilities. This task involves understanding how to set up and configure the Wazuh platform on our infrastructure.

**Comment by Blindspot22** [comment]
@NkwaTambe No Description ??
If I'm asked to review or work on such a ticket, I would love to have a small description(Aim) on what is happening or what has been done so far.
